spring.application.name=ttproject
server.port=8080

# spring.datasource.url=jdbc:mysql://localhost:3306/ttproject
# spring.datasource.username=root
# spring.datasource.password=Palleyaksha@123

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d6g11mp5pdvs73c73qn0-a/ttbackend}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ttbackend_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:uK6dNx084nWWZnb1uQHuoepnE19Lsw8U}

spring.jpa.hibernate.ddl-auto=update